from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)  
    url = models.URLField(null=True, blank=True) 
    github = models.URLField(null=True, blank=True) 
    image = models.ImageField(upload_to='projects/',null=True, blank=True)  
    subtitle = models.TextField(null=True, blank=True)  
    content1 = models.TextField(null=True, blank=True)  
    content2 = models.TextField(null=True, blank=True)  
    content3 = models.TextField(null=True, blank=True)  
    stack1 = models.CharField(max_length=50,null=True, blank=True)  
    stack2 = models.CharField(max_length=50,null=True, blank=True)  
    stack3 = models.CharField(max_length=50,null=True, blank=True)  
    stack4 = models.CharField(max_length=50,null=True, blank=True)  
    stack5 = models.CharField(max_length=50,null=True, blank=True)  
    stack6 = models.CharField(max_length=50,null=True, blank=True)  
    stack7 = models.CharField(max_length=50,null=True, blank=True)  
    stack8 = models.CharField(max_length=50,null=True, blank=True)  
    stack9 = models.CharField(max_length=50,null=True, blank=True)  
    stack10 = models.CharField(max_length=50,null=True, blank=True)  
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Education(models.Model):
    degree = models.CharField(max_length=100)  
    major = models.CharField(max_length=50,null=True, blank=True)  
    school = models.CharField(max_length=50,null=True, blank=True)
    date = models.CharField(max_length=50,null=True, blank=True)
    course = models.CharField(max_length=255,null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Work(models.Model):
    title = models.CharField(max_length=100)  
    position = models.CharField(max_length=100,null=True, blank=True)  
    duration = models.CharField(max_length=100,null=True, blank=True)
    url = models.URLField(null=True, blank=True) 
    github = models.URLField(null=True, blank=True) 
    image = models.ImageField(upload_to='works/',null=True, blank=True)  
    subtitle = models.TextField(null=True, blank=True)  
    content1 = models.TextField(null=True, blank=True)  
    content2 = models.TextField(null=True, blank=True)  
    content3 = models.TextField(null=True, blank=True)  
    stack1 = models.CharField(max_length=50,null=True, blank=True)  
    stack2 = models.CharField(max_length=50,null=True, blank=True)
    stack3 = models.CharField(max_length=50,null=True, blank=True)
    stack4 = models.CharField(max_length=50,null=True, blank=True)
    stack5 = models.CharField(max_length=50,null=True, blank=True)
    stack6 = models.CharField(max_length=50,null=True, blank=True)
    stack7 = models.CharField(max_length=50,null=True, blank=True)
    stack8 = models.CharField(max_length=50,null=True, blank=True)
    stack9 = models.CharField(max_length=50,null=True, blank=True)
    stack10 = models.CharField(max_length=50,null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)