# Generated by Django 5.1.4 on 2024-12-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('github', models.URLField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('subtitle', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('stack1', models.CharField(max_length=50)),
                ('stack2', models.CharField(max_length=50)),
                ('stack3', models.CharField(max_length=50)),
                ('stack4', models.CharField(max_length=50)),
                ('stack5', models.CharField(max_length=50)),
                ('stack6', models.CharField(max_length=50)),
                ('stack7', models.CharField(max_length=50)),
                ('stack8', models.CharField(max_length=50)),
                ('stack9', models.CharField(max_length=50)),
                ('stack10', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('github', models.URLField()),
                ('image', models.ImageField(upload_to='works/')),
                ('subtitle', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('stack1', models.CharField(max_length=50)),
                ('stack2', models.CharField(max_length=50)),
                ('stack3', models.CharField(max_length=50)),
                ('stack4', models.CharField(max_length=50)),
                ('stack5', models.CharField(max_length=50)),
                ('stack6', models.CharField(max_length=50)),
                ('stack7', models.CharField(max_length=50)),
                ('stack8', models.CharField(max_length=50)),
                ('stack9', models.CharField(max_length=50)),
                ('stack10', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
